@extends('eis.app')
@section('title', 'Step 2: Liabilities & Revenue')

@section('content')
<div class="card shadow-sm border-0">
    <div class="card-header bg-success text-white">
        <h5 class="mb-0">Step 2 of 2: Liabilities & Operations</h5>
    </div>
    <div class="card-body">
        <div class="progress mb-4" style="height: 25px;">
            <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
                <strong>100% Complete</strong>
            </div>
        </div>
        <form action="{{ route('eis.postStepTwo') }}" method="POST">
            @csrf
            
            <h6 class="text-muted border-bottom pb-2 mb-3">Liabilities Data</h6>
            
            <div class="mb-3">
                <label for="current_liabilities" class="form-label">Current Liabilities (USD)</label>
                <input type="number" step="0.01" class="form-control @error('current_liabilities') is-invalid @enderror" id="current_liabilities" name="current_liabilities" value="{{ old('current_liabilities') }}" required placeholder="e.g. 50000.00">
                @error('current_liabilities')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
                <div class="form-text">Short-term debts or obligations due within one year.</div>
            </div>

            <div class="mb-4">
                <label for="total_liabilities" class="form-label">Total Liabilities (USD)</label>
                <input type="number" step="0.01" class="form-control @error('total_liabilities') is-invalid @enderror" id="total_liabilities" name="total_liabilities" value="{{ old('total_liabilities') }}" required placeholder="e.g. 200000.00">
                @error('total_liabilities')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
                <div class="form-text">Total amount of all debts and obligations.</div>
            </div>

            <h6 class="text-muted border-bottom pb-2 mb-3 mt-4">Operational Data</h6>

            <div class="mb-3">
                <label for="total_revenue" class="form-label">Total Revenue (USD)</label>
                <input type="number" step="0.01" class="form-control @error('total_revenue') is-invalid @enderror" id="total_revenue" name="total_revenue" value="{{ old('total_revenue') }}" required placeholder="e.g. 300000.00">
                @error('total_revenue')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
                <div class="form-text">Total income generated by the entity's operations.</div>
            </div>

            <div class="mb-4">
                <label for="total_operating_expenses" class="form-label">Total Operating Expenses (USD)</label>
                <input type="number" step="0.01" class="form-control @error('total_operating_expenses') is-invalid @enderror" id="total_operating_expenses" name="total_operating_expenses" value="{{ old('total_operating_expenses') }}" required placeholder="e.g. 250000.00">
                @error('total_operating_expenses')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
                <div class="form-text">Total expenses incurred during normal operations.</div>
            </div>

            <div class="d-flex justify-content-between mt-4">
                <a href="{{ route('eis.stepOne') }}" class="btn btn-outline-secondary">&laquo; Back</a>
                <button type="submit" class="btn btn-success btn-lg">Calculate EIS Score &raquo;</button>
            </div>
        </form>
    </div>
</div>
@endsection